spring.application.name=cybershield

# Postgres Database Properties
spring.datasource.url=jdbc:postgresql://pg-39da28b2-cybershield.b.aivencloud.com:15418/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_b2Un1kTL--z6g2n1MIm
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true