# General properties
spring.application.name=cybershield
server.servlet.context-path=/cybershield
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=TRACE

# Logging
logging.level.root=INFO
logging.level.dev.group.cybershield=DEBUG

#Redis Properties
spring.data.redis.url=${env.spring.data.redis.url}

# Postgres Database Properties
spring.datasource.url=${env.spring.datasource.url}
spring.datasource.username=${env.spring.datasource.username}
spring.datasource.password=${env.spring.datasource.password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Hikari Connection Pool
logging.level.com.zaxxer.hikari=DEBUG
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Number of questions for quiz
number.of.question.in.quiz=4

# Frontend
cybershield.frontend.url= http://localhost:5173

# Authentication and Authorisation configurations
logging.level.org.springframework.security=TRACE

# Google OAuth2 Client Configuration
oauth.clients.google.clientsId=${env.oauth.clients.google.clientsId}
oauth.clients.google.clientSecret=${env.oauth.clients.google.clientSecret}
oauth.clients.google.grantType=authorization_code_with_pkce
oauth.clients.google.redirectUrl=http://localhost:5173/auth/login
oauth.clients.google.scope=email profile
oauth.clients.google.authUrl=https://accounts.google.com/o/oauth2/v2/auth/
oauth.clients.google.tokenUrl=https://oauth2.googleapis.com/token
oauth.clients.google.userInfoUrls=https://www.googleapis.com/oauth2/v3/userinfo

# GitHub OAuth2 Client Configuration
oauth.clients.github.clientsId=${env.oauth.clients.github.clientsId}
oauth.clients.github.clientSecret=${env.oauth.clients.github.clientSecret}
oauth.clients.github.grantType=authorization_code
oauth.clients.github.redirectUrl=http://localhost:5173/auth/login
oauth.clients.github.scope=user email openid
oauth.clients.github.authUrl=https://github.com/login/oauth/authorize
oauth.clients.github.tokenUrl=https://github.com/login/oauth/access_token
oauth.clients.github.userInfoUrls=https://api.github.com/user,https://api.github.com/user/emails

# Facebook OAuth2 Client Configuration
oauth.clients.facebook.clientsId=${env.oauth.clients.facebook.clientsId}
oauth.clients.facebook.clientSecret=${env.oauth.clients.facebook.clientSecret}
oauth.clients.facebook.grantType=authorization_code_with_pkce
oauth.clients.facebook.redirectUrl=http://localhost:5173/auth/login
oauth.clients.facebook.scope=public_profile
oauth.clients.facebook.authUrl=https://www.facebook.com/v12.0/dialog/oauth
oauth.clients.facebook.tokenUrl=https://graph.facebook.com/v12.0/oauth/access_token
oauth.clients.facebook.userInfoUrls=https://graph.facebook.com/me



